apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: {{.Values.global.namespace}}
  labels:
    component: sample-app
spec:
  ports:
    - name: api
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    component: sample-app
